"""Real HTTP /WanderingSwordsGuide/ browser behavior; no set_content fixtures."""
from pathlib import Path
from functools import partial
from http.server import ThreadingHTTPServer, SimpleHTTPRequestHandler
import json, os, shutil, threading, tempfile
from playwright.sync_api import sync_playwright, expect

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'test-results'
OUT.mkdir(exist_ok=True)
results = []
KEY = 'wandering-swords-guide:v1'
class Handler(SimpleHTTPRequestHandler):
    def log_message(self, *_): pass

def check(name, condition=True):
    assert condition, name
    results.append(name)
    print('PASS', name, flush=True)

with tempfile.TemporaryDirectory() as directory:
    (Path(directory) / 'WanderingSwordsGuide').symlink_to(ROOT / 'dist', target_is_directory=True)
    server = ThreadingHTTPServer(('127.0.0.1', 0), partial(Handler, directory=directory))
    threading.Thread(target=server.serve_forever, daemon=True).start()
    url = f'http://127.0.0.1:{server.server_port}/WanderingSwordsGuide/'
    with sync_playwright() as p:
        executable = os.environ.get('BROWSER_EXECUTABLE_PATH') or shutil.which('chromium')
        options = {'headless': True, 'args': ['--no-sandbox']}
        if executable: options['executable_path'] = executable
        browser = p.chromium.launch(**options)
        context = browser.new_context(viewport={'width': 1440, 'height': 1000}, accept_downloads=True)
        page = context.new_page(); errors = []
        page.on('pageerror', lambda e: errors.append(str(e)))
        response = page.goto(url + '#chapter=ch-7&view=route')
        expect(page.locator('.task-card').first).to_be_visible()
        check('production build serves through real HTTP Pages subpath', response.status == 200)
        page.screenshot(path=OUT / 'desktop.png', full_page=False)
        first = page.locator('.task-card').first
        task_id = first.get_attribute('id').removeprefix('task-')
        first.locator('.complete-button').click()
        page.wait_for_function('(k) => JSON.parse(localStorage.getItem(k)).statuses["上-507"] === "done"', arg=KEY)
        page.reload(); expect(page.locator(f'[id="task-{task_id}"] .complete-button')).to_have_attribute('aria-pressed', 'true')
        check('completion survives a real browser reload')
        page.locator('.task-card').nth(1).get_by_role('button', name='本轮跳过').click()
        expect(page.locator('.list-toolbar')).to_contain_text('跳过 1')
        page.get_by_label('只看待办').check(); expect(page.locator('.task-card.done')).to_have_count(0); expect(page.locator('.task-card.skipped')).to_have_count(0)
        check('skipped is not completed; pending filter hides both')
        page.get_by_label('只看待办').uncheck()
        page.locator('#chapter-note').fill('存档：千陵渡调查之前\n先找陈麟熙。')
        page.wait_for_function('(k) => JSON.parse(localStorage.getItem(k)).notes["ch-7"]?.includes("千陵渡")', arg=KEY)
        page.reload(); expect(page.locator('#chapter-note')).to_have_value('存档：千陵渡调查之前\n先找陈麟熙。')
        check('chapter notes persist independently')
        page.locator('.task-card').first.get_by_role('button', name='展开步骤').click()
        expect(page.locator('.task-details').first).to_be_visible()
        page.locator('.task-card').first.locator('.source-button').click()
        expect(page.locator('dialog .source-lines')).to_be_visible()
        expect(page.locator('dialog .source-range')).to_contain_text('507')
        check('task source opens original lines, not rewritten summary')
        page.keyboard.press('Escape'); expect(page.locator('dialog')).not_to_be_visible()
        expect(page.locator('.task-card').first.locator('.source-button')).to_be_focused()
        check('dialog Escape closes and restores focus')
        page.locator('#guide-search').fill('陈麟熙 义正言辞')
        expect(page.locator('.task-card')).to_have_count(1)
        page.reload(); expect(page.locator('#guide-search')).to_have_value('陈麟熙 义正言辞')
        page.locator('.task-card').get_by_role('button', name='定位章节').click()
        expect(page.locator('[id="task-上-537"]')).to_have_class('task-card todo highlighted')
        check('search and deep link restore via hash; locate reveals exact task')
        page.locator('#guide-search').fill('没有这个任务xyz')
        expect(page.get_by_text('没有找到对应内容')).to_be_visible()
        page.get_by_role('button', name='清空搜索', exact=True).first.click()
        expect(page.locator('#guide-search')).to_be_focused()
        check('no-results and explicit search clear recover')
        page.locator('#guide-search').evaluate("e => {e.dispatchEvent(new CompositionEvent('compositionstart',{bubbles:true})); e.value='陈'; e.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true}));}")
        check('IME partial composition does not commit route search', 'q=' not in page.url)
        page.locator('#guide-search').evaluate("e => {e.value='陈麟熙';e.dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}));}")
        expect(page.locator('.chapter-header h2')).to_contain_text('陈麟熙')
        page.get_by_role('button', name='清空搜索', exact=True).first.click()
        page.get_by_role('button', name='打开行囊与进度备份').click()
        expect(page.locator('dialog')).to_be_visible()
        page.screenshot(path=OUT / 'settings.png')
        page.locator('input[name=branch][value=merchant]').check()
        page.get_by_label('显示顺路见闻与收集挑战').check()
        with page.expect_download() as download:
            page.get_by_role('button', name='导出进度', exact=True).click()
        exported = json.loads(Path(download.value.path()).read_text())
        check('downloaded backup contains route, notes, and task statuses', exported['branch'] == 'merchant' and exported['notes']['ch-7'].startswith('存档'))
        page.locator('input[type=file]').set_input_files({'name': 'bad.json', 'mimeType': 'application/json', 'buffer': b'{}'})
        expect(page.locator('.inline-error')).to_contain_text('不是本路书')
        check('invalid import is rejected without replacing progress')
        imported = {**exported, 'branch': 'medicine', 'notes': {'ch-7': '导入测试'}, 'statuses': {'上-537': 'done'}}
        page.locator('input[type=file]').set_input_files({'name': 'valid.json', 'mimeType': 'application/json', 'buffer': json.dumps(imported).encode()})
        expect(page.get_by_role('button', name='确认替换进度')).to_be_visible()
        page.get_by_role('button', name='取消', exact=True).click()
        check('import preview cancel preserves current data', page.evaluate('(k) => JSON.parse(localStorage.getItem(k)).branch', KEY) == 'merchant')
        page.locator('input[type=file]').set_input_files({'name': 'valid.json', 'mimeType': 'application/json', 'buffer': json.dumps(imported).encode()})
        page.get_by_role('button', name='确认替换进度').click()
        expect(page.locator('#chapter-note')).to_have_value('导入测试')
        check('confirmed import safely replaces progress')
        page.get_by_role('button', name='打开行囊与进度备份').click()
        page.get_by_role('button', name='重置本轮旅程', exact=True).click()
        page.get_by_role('button', name='取消', exact=True).click(); page.keyboard.press('Escape')
        expect(page.locator('#chapter-note')).to_have_value('导入测试')
        check('reset cancel does not destroy notes')
        other = context.new_page(); other.goto(url + '#chapter=ch-7&view=route')
        expect(other.locator('.task-card').first).to_be_visible()
        page.locator('.task-card').first.locator('.complete-button').click()
        expect(other.get_by_text('另一标签页已修改进度。本页暂停保存，避免相互覆盖。')).to_be_visible()
        other.get_by_role('button', name='加载另一页').click()
        expect(other.locator('.global-warning')).to_have_count(0)
        check('cross-tab changes pause writes until explicit resolution')
        other.close()
        page.route('**/source/guide.json', lambda route: route.abort())
        page.get_by_role('button', name='原文查阅', exact=True).click()
        expect(page.get_by_role('button', name='重新读取')).to_be_visible()
        page.unroute('**/source/guide.json')
        page.get_by_role('button', name='重新读取').click()
        expect(page.locator('.source-lines')).to_be_visible()
        page.locator('#source-section').select_option('20')
        expect(page.locator('.source-range')).to_contain_text('545')
        check('source fetch failure supports retry; native section select works')
        for width in [320, 390, 768, 1024, 1440]:
            page.set_viewport_size({'width': width, 'height': 900})
            page.goto(url + '#chapter=ch-7&view=route'); expect(page.locator('.task-card').first).to_be_visible()
            check(f'{width}px main layout has no horizontal overflow', page.evaluate('document.documentElement.scrollWidth <= innerWidth'))
            if width < 920:
                page.get_by_role('button', name='打开章节目录').click()
                expect(page.locator('dialog .chapter-nav')).to_be_visible()
                page.locator('dialog .chapter-nav a').filter(has_text='南疆风云').click()
                expect(page.locator('.chapter-header h2')).to_have_text('南疆风云')
                check(f'{width}px mobile directory navigates with same chapter data')
            if width == 390: page.screenshot(path=OUT / 'mobile.png', full_page=False)
        page.goto(url + '#chapter=ch-7&view=route')
        page.add_script_tag(path=str(ROOT / 'node_modules/axe-core/axe.min.js'))
        a11y = page.evaluate("async () => (await axe.run(document, {runOnly:{type:'tag', values:['wcag2a','wcag2aa','wcag21aa']}})).violations")
        (OUT / 'accessibility.json').write_text(json.dumps(a11y, ensure_ascii=False, indent=2))
        check('axe main page has no A/AA violations', not a11y)
        page.get_by_role('button', name='打开行囊与进度备份').click()
        a11y_dialog = page.evaluate("async () => (await axe.run(document, {runOnly:{type:'tag', values:['wcag2a','wcag2aa','wcag21aa']}})).violations")
        (OUT / 'accessibility-dialog.json').write_text(json.dumps(a11y_dialog, ensure_ascii=False, indent=2))
        check('axe settings dialog has no A/AA violations', not a11y_dialog)
        page.get_by_role('button', name='查看江湖地图').click()
        expect(page.locator('.map-container img')).to_be_visible()
        check('local world-map image decodes', page.locator('.map-container img').evaluate('e => e.complete && e.naturalWidth > 0'))
        page.keyboard.press('Escape')
        page.emulate_media(reduced_motion='reduce'); check('reduced motion disables transitions', page.locator('.continue-card').evaluate('e => getComputedStyle(e).transitionDuration') == '0s')
        check('no uncaught browser runtime errors', not errors)
        broken = browser.new_context()
        broken.add_init_script(f"localStorage.setItem('{KEY}', '{{broken');")
        bp = broken.new_page(); bp.goto(url); expect(bp.locator('.global-warning')).to_contain_text('损坏')
        bp.locator('.complete-button').first.click(); bp.wait_for_timeout(300)
        check('corrupt stored bytes are retained instead of overwritten', bp.evaluate('(k) => localStorage.getItem(k)', KEY) == '{broken')
        broken.close()
        quota = browser.new_context(); quota.add_init_script("Storage.prototype.setItem = function(){throw new DOMException('quota','QuotaExceededError')}")
        qp = quota.new_page(); qp.goto(url); qp.locator('.complete-button').first.click()
        expect(qp.locator('.global-warning')).to_contain_text('保存失败')
        check('storage write failures leave visible recovery instructions')
        quota.close(); context.close(); browser.close()
    server.shutdown()
report = {'mode': 'real-http-subpath', 'checks': len(results), 'passed': results, 'browserErrors': errors}
(OUT / 'browser-report.json').write_text(json.dumps(report, ensure_ascii=False, indent=2))
print(f'All {len(results)} browser checks passed.')
